### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/macnamer#3]
Typo located [here](https://github.com/grahamgilbert/macnamer/wiki/Installation-on-Ubuntu#create-the-virtual-environment).

The following `pip install django-bootstap_toolkit` needs to be changed to `pip install django-bootstrap_toolkit`

I'm not much of a programmer but I'll help the community with proofreading.

Thanks Graham

**Comment by grahamgilbert** [comment]
Thanks, I've fixed this now.
